### ISSUE TITLE
Wrong class name in doc

### ISSUE THREAD

**Issue by petrparolek** [instante/bootstrap3renderer#8]
Did you mean BootstrapRenderer instead of BootstrapFormFactory?

**Comment by richard-ejem** [comment]
If you mean here https://github.com/instante/bootstrap3renderer/blob/master/docs/index.md#instante-bootstrap-3-renderer then no. It wouldn't work this way with the renderer as a service, because unfortunately form renderer is not injected from service container into a Nette Form automatically, the recommended practice is to instantiate a form and inject its dependencies via factory.
